server.port=8085
spring.thymeleaf.cache=false

# ?? ? ? ?? ?? ?? ? ?? ?? ?? ???
spring.datasource.generate-unique-name=false
spring.main.allow-bean-definition-overriding=true

# MongoDB Atlas ?? ?? (tacocloud: ?? ?? ????? ?????)
spring.data.mongodb.uri=mongodb+srv://ysi:${MONGODB_PASSWORD}@cluster0.c0omuo0.mongodb.net/tacoclouddb